2015-06-23 11:54:44,772 my_lib.py[line:280] ERROR [1;31;40m**Error**[0m 输入的选项不正确.

2015-06-23 11:54:45,020 my_lib.py[line:280] ERROR [1;31;40m**Error**[0m 输入的选项不正确.

2015-06-23 11:55:49,285 my_lib.py[line:280] ERROR [1;31;40m**Error**[0m 输入的选项不正确.

2015-06-23 11:55:55,373 my_lib.py[line:277] INFO 

[1;32;40m**Success**[0m Good Luck Boys.........

2015-06-23 11:56:06,141 my_lib.py[line:280] ERROR [1;31;40m**Error**[0m 输入的选项不正确.

2015-06-23 11:56:17,568 my_lib.py[line:280] ERROR [1;31;40m**Error**[0m 输入的选项不正确.

2015-06-23 11:56:20,387 my_lib.py[line:280] ERROR [1;31;40m**Error**[0m 输入的选项不正确.

2015-06-23 11:56:24,594 my_lib.py[line:280] ERROR [1;31;40m**Error**[0m 输入的选项不正确.

2015-06-23 11:56:30,748 my_lib.py[line:277] INFO 

[1;32;40m**Success**[0m Good Luck Boys.........

2015-06-23 11:57:59,212 my_lib.py[line:277] INFO [1;32;40m**Success**[0m machine ip: 10.139.20.209  网络畅通.

2015-06-23 11:57:59,212 my_lib.py[line:277] INFO [1;32;40m**Success**[0m vlan ip: 10.149.224.34  网络畅通.

2015-06-23 11:57:59,213 my_lib.py[line:277] INFO [1;32;40m**Success**[0m vlan ip: 10.139.224.34  网络畅通.

2015-06-23 11:57:59,213 my_lib.py[line:277] INFO [1;32;40m**Success**[0m machine ip: 10.149.20.209  网络畅通.

2015-06-23 11:58:19,988 my_lib.py[line:277] INFO 

[1;32;40m**Success**[0m Good Luck Boys.........

2015-06-23 11:58:32,392 my_lib.py[line:280] ERROR 模块不存在，无法获取信息!
2015-06-23 11:58:32,393 my_lib.py[line:280] ERROR [1;31;40m**Error**[0m 无法获取主机信息.

2015-06-23 11:58:40,795 my_lib.py[line:277] INFO [1;32;40m**Success**[0m machine ip: 10.139.20.209  网络畅通.

2015-06-23 11:58:40,795 my_lib.py[line:277] INFO [1;32;40m**Success**[0m vlan ip: 10.149.224.34  网络畅通.

2015-06-23 11:58:40,795 my_lib.py[line:277] INFO [1;32;40m**Success**[0m vlan ip: 10.139.224.34  网络畅通.

2015-06-23 11:58:40,796 my_lib.py[line:277] INFO [1;32;40m**Success**[0m machine ip: 10.149.20.209  网络畅通.

2015-06-23 11:58:53,435 my_lib.py[line:277] INFO 

[1;32;40m**Success**[0m Good Luck Boys.........

2015-06-23 12:02:03,180 my_lib.py[line:280] ERROR [1;31;40m**Error**[0m 输入的ip地址非法!

2015-06-23 12:02:39,350 my_lib.py[line:277] INFO [1;32;40m**Success**[0m  远程主机10.149.27.183 vlan ip配置清理成功!

2015-06-23 12:08:07,084 my_lib.py[line:280] ERROR Incompatible version (1.5 instead of 2.0)
2015-06-23 13:32:02,075 my_lib.py[line:280] ERROR Incompatible version (1.5 instead of 2.0)
2015-06-23 13:35:00,419 my_lib.py[line:277] INFO [1;32;40m**Success**[0m  远程主机10.149.20.209 vlan ip配置清理成功!

2015-06-23 13:36:13,494 my_lib.py[line:280] ERROR [1;31;40m**Error**[0m 输入的ip地址非法!

2015-06-23 13:36:18,429 my_lib.py[line:280] ERROR [1;31;40m**Error**[0m 输入的ip地址非法!

2015-06-23 13:36:20,341 my_lib.py[line:277] INFO exit
2015-06-23 13:36:38,564 my_lib.py[line:280] ERROR 模块不存在，无法获取信息!
2015-06-23 13:36:38,564 my_lib.py[line:280] ERROR [1;31;40m**Error**[0m 无法获取主机信息.

2015-06-23 13:37:48,211 my_lib.py[line:277] INFO [1;32;40m**Success**[0m 远程主机vlan ip部署成功!

2015-06-23 13:37:48,212 my_lib.py[line:277] INFO [1;32;40m**Success**[0m 配置vlan ip 成功.

2015-06-23 13:37:48,250 my_lib.py[line:277] INFO [1;32;40m**Success**[0m 发送邮件 成功.

2015-06-23 13:39:39,392 my_lib.py[line:277] INFO [1;32;40m**Success**[0m  远程主机10.149.20.209 vlan ip配置清理成功!

2015-06-23 13:39:55,951 my_lib.py[line:277] INFO exit
2015-06-23 13:40:41,174 my_lib.py[line:277] INFO 

[1;32;40m**Success**[0m Good Luck Boys.........

2015-06-23 13:40:54,932 my_lib.py[line:280] ERROR 模块不存在，无法获取信息!
2015-06-23 13:40:54,932 my_lib.py[line:280] ERROR [1;31;40m**Error**[0m 无法获取主机信息.

2015-06-23 13:40:56,979 my_lib.py[line:280] ERROR 模块不存在，无法获取信息!
2015-06-23 13:40:56,979 my_lib.py[line:280] ERROR [1;31;40m**Error**[0m 无法获取主机信息.

2015-06-23 13:41:48,431 my_lib.py[line:277] INFO [1;32;40m**Success**[0m bizop平台信息更新成功.

2015-06-23 13:41:48,432 my_lib.py[line:277] INFO [1;32;40m**Success**[0m 切换vlan ip 成功!

2015-06-23 13:41:48,469 my_lib.py[line:277] INFO [1;32;40m**Success**[0m 发送邮件 成功!

2015-06-23 13:43:45,131 my_lib.py[line:277] INFO [1;32;40m**Success**[0m  远程主机10.149.27.183 vlan ip配置清理成功!

2015-06-23 13:44:10,282 my_lib.py[line:277] INFO exit
2015-06-23 13:45:06,543 my_lib.py[line:277] INFO [1;32;40m**Success**[0m bizop平台信息更新成功.

2015-06-23 13:45:06,544 my_lib.py[line:277] INFO [1;32;40m**Success**[0m 切换vlan ip 成功!

2015-06-23 13:45:06,640 my_lib.py[line:277] INFO [1;32;40m**Success**[0m 发送邮件 成功!

2015-06-23 13:48:19,244 my_lib.py[line:277] INFO [1;32;40m【 请输入y/n 】 [0m
2015-06-23 13:48:21,037 my_lib.py[line:277] INFO 

[1;32;40m**Success**[0m Good Luck Boys.........

2015-06-23 13:51:34,708 my_lib.py[line:280] ERROR 模块不存在，无法获取信息!
2015-06-23 13:51:34,708 my_lib.py[line:280] ERROR [1;31;40m**Error**[0m 无法获取主机信息.

2015-06-23 13:52:28,468 my_lib.py[line:277] INFO 

[1;32;40m**Success**[0m Good Luck Boys.........

2015-06-23 13:52:49,932 my_lib.py[line:280] ERROR [1;31;40m**Error**[0m 输入的选项不正确.

2015-06-23 13:53:02,958 my_lib.py[line:280] ERROR [1;31;40m**Error**[0m 该主机在bizop平台没有配置vlan ip.

2015-06-23 13:53:02,959 my_lib.py[line:277] INFO [1;31;40m**Error**[0m  按照ip方式部署vlan ip 失败!

2015-06-23 15:07:59,222 my_lib.py[line:277] INFO vlan ip 未配置!
2015-06-23 15:09:26,856 my_lib.py[line:277] INFO vlan ip 未配置!无法清理。
2015-06-23 15:10:17,680 my_lib.py[line:277] INFO [1;31;40m**Error**[0m vlan ip 未配置!无法清理.

2015-06-23 15:23:49,925 my_lib.py[line:280] ERROR Authentication failed.
2015-06-23 15:25:09,534 my_lib.py[line:281] ERROR Authentication failed.
2015-06-23 15:27:43,728 my_lib.py[line:284] ERROR 服务器无法访问，请核实.
2015-06-23 15:34:53,300 my_lib.py[line:296] ERROR [1;31;40m**Error**[0m 输入的选项不正确.

2015-06-23 15:35:22,532 my_lib.py[line:296] ERROR [1;31;40m**Error**[0m 输入的ip地址非法!

2015-06-23 15:35:25,778 my_lib.py[line:296] ERROR [1;31;40m**Error**[0m 输入的ip地址非法!

2015-06-23 15:35:26,611 my_lib.py[line:296] ERROR [1;31;40m**Error**[0m 输入的ip地址非法!

2015-06-23 15:35:26,898 my_lib.py[line:296] ERROR [1;31;40m**Error**[0m 输入的ip地址非法!

2015-06-23 15:35:29,442 my_lib.py[line:296] ERROR [1;31;40m**Error**[0m 输入的ip地址非法!

2015-06-23 15:35:30,290 my_lib.py[line:296] ERROR [1;31;40m**Error**[0m 输入的ip地址非法!

2015-06-23 15:35:36,050 my_lib.py[line:296] ERROR [1;31;40m**Error**[0m 输入的ip地址非法!

2015-06-23 15:48:06,497 my_lib.py[line:296] ERROR [1;31;40m**Error**[0m 网络不可达!

2015-06-23 15:48:08,774 my_lib.py[line:296] ERROR [1;31;40m**Error**[0m 输入的ip地址非法!

2015-06-23 15:48:15,205 my_lib.py[line:293] INFO exit
2015-06-23 15:49:57,347 my_lib.py[line:296] ERROR [1;31;40m**Error**[0m 输入的选项不正确.

2015-06-23 15:50:01,390 my_lib.py[line:296] ERROR [1;31;40m**Error**[0m 此选项不支持vlan ip切换，请更换选项!

2015-06-23 15:50:01,391 my_lib.py[line:296] ERROR [1;31;40m**Error**[0m 切换server ip 失败!

2015-06-23 15:50:19,385 my_lib.py[line:296] ERROR 模块不存在，无法获取信息!
2015-06-23 15:50:19,385 my_lib.py[line:296] ERROR [1;31;40m**Error**[0m 无法获取主机信息.

2015-06-23 15:50:20,983 my_lib.py[line:293] INFO exit
2015-06-23 15:50:32,227 my_lib.py[line:293] INFO [1;31;40m**Success**[0m 退出部署.

2015-06-23 15:59:45,039 my_lib.py[line:296] ERROR [1;31;40m**Error**[0m 输入的ip地址非法!

2015-06-23 15:59:46,581 my_lib.py[line:296] ERROR [1;31;40m**Error**[0m 输入的ip地址非法!

2015-06-23 15:59:49,342 my_lib.py[line:296] ERROR [1;31;40m**Error**[0m 输入的ip地址非法!

2015-06-23 15:59:52,746 my_lib.py[line:296] ERROR [1;31;40m**Error**[0m 网络不可达!

2015-06-23 15:59:55,312 my_lib.py[line:296] ERROR [1;31;40m**Error**[0m 网络不可达!

2015-06-23 16:00:41,940 my_lib.py[line:293] INFO [1;31;40m**Error**[0m vlan ip 未配置!无法清理.

2015-06-23 16:32:44,585 my_lib.py[line:296] ERROR [1;31;40m**Error**[0m 输入的ip地址非法!

2015-06-23 16:32:55,858 my_lib.py[line:293] INFO [1;31;40m**Error**[0m vlan ip 未配置!无法清理.

2015-06-23 16:33:07,862 my_lib.py[line:293] INFO [1;31;40m**Error**[0m vlan ip 未配置!无法清理.

2015-06-23 16:35:23,479 my_lib.py[line:296] ERROR 
2015-06-23 16:36:39,414 my_lib.py[line:296] ERROR Incompatible version (1.5 instead of 2.0)
2015-06-23 16:37:09,465 my_lib.py[line:296] ERROR [1;31;40m**Error**[0m 网络不可达!

2015-06-23 16:37:18,071 my_lib.py[line:296] ERROR [1;31;40m**Error**[0m 网络不可达!

2015-06-23 16:38:39,639 my_lib.py[line:293] INFO 

[1;32;40m**Success**[0m Good Luck Boys.........

2015-06-23 16:39:28,274 my_lib.py[line:296] ERROR 
2015-06-23 16:42:20,535 my_lib.py[line:296] ERROR [1;31;40m**Error**[0m 输入的选项不正确.

2015-06-23 16:42:36,279 my_lib.py[line:296] ERROR 模块不存在，无法获取信息!
2015-06-23 16:42:36,279 my_lib.py[line:296] ERROR [1;31;40m**Error**[0m 无法获取主机信息.

2015-06-23 16:43:14,685 my_lib.py[line:296] ERROR [1;31;40m**Error**[0m 备机宕机，无法切换!

2015-06-23 16:43:14,686 my_lib.py[line:296] ERROR [1;31;40m**Error**[0m 切换server ip 失败!

2015-06-23 16:43:34,601 my_lib.py[line:296] ERROR 模块不存在，无法获取信息!
2015-06-23 16:43:34,602 my_lib.py[line:296] ERROR [1;31;40m**Error**[0m 无法获取主机信息.

2015-06-23 16:43:39,525 my_lib.py[line:296] ERROR [1;31;40m**Error**[0m 备机宕机，无法切换!

2015-06-23 16:43:39,526 my_lib.py[line:296] ERROR [1;31;40m**Error**[0m 切换server ip 失败!

2015-06-23 16:44:21,529 my_lib.py[line:296] ERROR [1;31;40m**Error**[0m 非一主一备模式,此脚本不支持!

2015-06-23 16:44:21,529 my_lib.py[line:296] ERROR [1;31;40m**Error**[0m 无法获取主机信息.

2015-06-23 16:44:49,994 my_lib.py[line:293] INFO 

[1;32;40m**Success**[0m Good Luck Boys.........

2015-06-23 16:45:20,188 my_lib.py[line:296] ERROR [1;31;40m**Error**[0m 切换server ip 失败!

2015-06-23 16:45:21,711 my_lib.py[line:296] ERROR [1;31;40m**Error**[0m 此选项不支持vlan ip切换，请更换选项!

2015-06-23 16:45:21,712 my_lib.py[line:296] ERROR [1;31;40m**Error**[0m 切换server ip 失败!

2015-06-23 16:45:33,165 my_lib.py[line:296] ERROR 模块不存在，无法获取信息!
2015-06-23 16:45:33,166 my_lib.py[line:296] ERROR [1;31;40m**Error**[0m 无法获取主机信息.

2015-06-23 16:45:36,437 my_lib.py[line:293] INFO 

[1;32;40m**Success**[0m Good Luck Boys.........

2015-06-23 16:46:31,447 my_lib.py[line:296] ERROR [1;31;40m**Error**[0m 此选项不支持vlan ip切换，请更换选项!

2015-06-23 16:46:31,448 my_lib.py[line:296] ERROR [1;31;40m**Error**[0m 切换server ip 失败!

2015-06-23 16:47:03,503 my_lib.py[line:296] ERROR 模块不存在，无法获取信息!
2015-06-23 16:47:03,504 my_lib.py[line:296] ERROR [1;31;40m**Error**[0m 无法获取主机信息.

2015-06-23 16:47:07,523 my_lib.py[line:296] ERROR [1;31;40m**Error**[0m 此选项不支持vlan ip切换，请更换选项!

2015-06-23 16:47:07,523 my_lib.py[line:296] ERROR [1;31;40m**Error**[0m 切换server ip 失败!

2015-06-23 16:47:12,696 my_lib.py[line:296] ERROR 模块不存在，无法获取信息!
2015-06-23 16:47:12,696 my_lib.py[line:296] ERROR [1;31;40m**Error**[0m 无法获取主机信息.

2015-06-23 16:48:15,520 my_lib.py[line:296] ERROR 
2015-06-23 19:16:48,478 my_lib.py[line:296] ERROR [1;31;40m**Error**[0m 网络不可达!

2015-06-23 19:18:06,579 my_lib.py[line:296] ERROR [1;31;40m**Error**[0m 网络不可达!

2015-06-23 19:19:03,249 my_lib.py[line:296] ERROR [1;31;40m**Error**[0m 网络不可达!

2015-06-23 19:19:28,036 my_lib.py[line:293] INFO exit
2015-06-23 19:19:28,349 my_lib.py[line:296] ERROR [1;31;40m**Error**[0m 输入的选项不正确.

2015-06-23 19:19:28,532 my_lib.py[line:296] ERROR [1;31;40m**Error**[0m 输入的选项不正确.

2015-06-23 19:19:52,403 my_lib.py[line:293] INFO 

[1;32;40m**Success**[0m Good Luck Boys.........

2015-06-23 19:20:24,692 my_lib.py[line:296] ERROR 
2015-06-23 19:21:13,883 my_lib.py[line:296] ERROR [1;31;40m**Error**[0m vlan ip已在本地网络中其他机器配置,请联系系统管理员

2015-06-23 19:21:34,117 my_lib.py[line:296] ERROR [1;31;40m**Error**[0m 配置vlan ip 失败!

2015-06-23 19:21:37,133 my_lib.py[line:293] INFO exit
2015-06-23 19:24:31,772 my_lib.py[line:293] INFO [1;32;40m【 请输入y/n 】 [0m
2015-06-23 19:25:15,855 my_lib.py[line:296] ERROR 
2015-06-23 19:27:43,927 my_lib.py[line:297] ERROR 
2015-06-23 19:38:48,859 my_lib.py[line:298] ERROR [1;31;40m**Error**[0m vlan ip已在本地网络中其他机器配置,请联系系统管理员

2015-06-23 19:38:54,412 my_lib.py[line:298] ERROR [1;31;40m**Error**[0m 配置vlan ip 失败!

2015-06-23 19:38:56,110 my_lib.py[line:295] INFO exit
2015-06-23 19:38:59,413 my_lib.py[line:298] ERROR [1;31;40m**Error**[0m 输入的ip地址非法!

2015-06-23 19:39:33,425 my_lib.py[line:295] INFO [1;32;40m**Success**[0m  远程主机10.139.20.209 vlan ip配置清理成功!

2015-06-23 19:40:42,513 my_lib.py[line:298] ERROR [1;31;40m**Error**[0m vlan ip已在本地网络中其他机器配置,请联系系统管理员

2015-06-23 19:40:46,607 my_lib.py[line:295] INFO exit
2015-06-23 19:41:20,221 my_lib.py[line:298] ERROR [1;31;40m**Error**[0m Traceback (most recent call last):
  File "/opt/opbin/tools/check_net.py", line 265, in <module>
    route_conf_info = get_main_table()
  File "/opt/opbin/tools/check_net.py", line 188, in get_main_table
    with open(route_info_file,'r') as f:
IOError: [Errno 2] No such file or directory: '/etc/sysconfig/network-scripts/eth2.route'
.

2015-06-23 19:44:43,555 my_lib.py[line:298] ERROR 
2015-06-23 19:45:28,002 my_lib.py[line:298] ERROR 
2015-06-23 19:47:48,710 my_lib.py[line:298] ERROR [1;31;40m**Error**[0m 输入的ip地址非法!

2015-06-23 19:48:35,546 my_lib.py[line:298] ERROR [1;31;40m**Error**[0m 输入的选项不正确.

2015-06-23 19:48:35,704 my_lib.py[line:298] ERROR [1;31;40m**Error**[0m 输入的选项不正确.

2015-06-23 19:48:59,896 my_lib.py[line:298] ERROR 
2015-06-23 19:54:56,528 my_lib.py[line:298] ERROR 
2015-06-23 19:57:00,218 my_lib.py[line:293] INFO [1;31;40m**Error**[0m vlan ip 未配置!无法清理.

2015-06-23 19:57:04,300 my_lib.py[line:293] INFO exit
2015-06-23 19:57:27,852 my_lib.py[line:296] ERROR 
2015-06-23 19:57:51,171 my_lib.py[line:296] ERROR [1;31;40m**Error**[0m vlan ip已在本地网络中其他机器配置,请联系系统管理员

2015-06-23 19:57:55,818 my_lib.py[line:296] ERROR [1;31;40m**Error**[0m 配置vlan ip 失败!

2015-06-23 19:57:57,709 my_lib.py[line:296] ERROR 模块不存在，无法获取信息!
2015-06-23 19:57:57,709 my_lib.py[line:296] ERROR [1;31;40m**Error**[0m 无法获取主机信息.

2015-06-23 19:57:59,234 my_lib.py[line:293] INFO exit
2015-06-23 19:58:17,051 my_lib.py[line:296] ERROR 
2015-06-23 21:51:32,452 my_lib.py[line:297] ERROR 
2015-06-23 21:52:50,110 my_lib.py[line:298] ERROR 
2015-06-23 21:53:40,953 my_lib.py[line:298] ERROR 
2015-06-23 22:07:56,851 my_lib.py[line:295] INFO [1;32;40m**Success**[0m  远程主机10.149.20.209 vlan ip配置清理成功!

2015-06-23 22:08:07,888 my_lib.py[line:298] ERROR [1;31;40m**Error**[0m 网络不可达!

2015-06-23 22:09:03,151 my_lib.py[line:298] ERROR [1;31;40m**Error**[0m 网络不可达!

2015-06-23 22:09:12,035 my_lib.py[line:295] INFO exit
2015-06-23 22:09:54,270 my_lib.py[line:295] INFO [1;32;40m**Success**[0m 远程主机vlan ip部署成功!

2015-06-23 22:09:54,271 my_lib.py[line:295] INFO [1;32;40m**Success**[0m 配置vlan ip 成功.

2015-06-23 22:09:54,290 my_lib.py[line:295] INFO [1;32;40m**Success**[0m 发送邮件 成功.

2015-06-23 22:10:54,035 my_lib.py[line:295] INFO [1;32;40m**Success**[0m bizop平台信息更新成功.

2015-06-23 22:10:54,036 my_lib.py[line:295] INFO [1;32;40m**Success**[0m 切换vlan ip 成功!

2015-06-23 22:10:54,047 my_lib.py[line:295] INFO [1;32;40m**Success**[0m 发送邮件 成功!

2015-06-23 22:18:21,585 my_lib.py[line:295] INFO 

[1;32;40m**Success**[0m Good Luck Boys.........

2015-06-23 22:18:58,097 my_lib.py[line:295] ERROR [1;31;40m**Error**[0m 此选项不支持vlan ip切换，请更换选项!

2015-06-23 22:18:58,098 my_lib.py[line:295] ERROR [1;31;40m**Error**[0m 切换server ip 失败!

